# Autogenerated wrapper script for eccodes_jll for aarch64-linux-musl-libgfortran5-cxx11
export bufr_compare, bufr_copy, bufr_count, bufr_dump, bufr_get, bufr_index_build, bufr_ls, bufr_set, codes_bufr_filter, codes_count, codes_export_resource, codes_info, codes_parser, codes_split_file, eccodes, eccodes_definitions, grib2ppm, grib_compare, grib_copy, grib_count, grib_dump, grib_filter, grib_get, grib_get_data, grib_histogram, grib_index_build, grib_ls, grib_set, gts_compare, gts_copy, gts_count, gts_dump, gts_filter, gts_get, gts_ls, libeccodes_f90

using CompilerSupportLibraries_jll
using libpng_jll
using OpenJpeg_jll
using libaec_jll
JLLWrappers.@generate_wrapper_header("eccodes")
JLLWrappers.@declare_library_product(eccodes, "libeccodes.so")
JLLWrappers.@declare_library_product(libeccodes_f90, "libeccodes_f90.so")
JLLWrappers.@declare_executable_product(bufr_compare)
JLLWrappers.@declare_executable_product(bufr_copy)
JLLWrappers.@declare_executable_product(bufr_count)
JLLWrappers.@declare_executable_product(bufr_dump)
JLLWrappers.@declare_executable_product(bufr_get)
JLLWrappers.@declare_executable_product(bufr_index_build)
JLLWrappers.@declare_executable_product(bufr_ls)
JLLWrappers.@declare_executable_product(bufr_set)
JLLWrappers.@declare_executable_product(codes_bufr_filter)
JLLWrappers.@declare_executable_product(codes_count)
JLLWrappers.@declare_executable_product(codes_export_resource)
JLLWrappers.@declare_executable_product(codes_info)
JLLWrappers.@declare_executable_product(codes_parser)
JLLWrappers.@declare_executable_product(codes_split_file)
JLLWrappers.@declare_file_product(eccodes_definitions)
JLLWrappers.@declare_executable_product(grib2ppm)
JLLWrappers.@declare_executable_product(grib_compare)
JLLWrappers.@declare_executable_product(grib_copy)
JLLWrappers.@declare_executable_product(grib_count)
JLLWrappers.@declare_executable_product(grib_dump)
JLLWrappers.@declare_executable_product(grib_filter)
JLLWrappers.@declare_executable_product(grib_get)
JLLWrappers.@declare_executable_product(grib_get_data)
JLLWrappers.@declare_executable_product(grib_histogram)
JLLWrappers.@declare_executable_product(grib_index_build)
JLLWrappers.@declare_executable_product(grib_ls)
JLLWrappers.@declare_executable_product(grib_set)
JLLWrappers.@declare_executable_product(gts_compare)
JLLWrappers.@declare_executable_product(gts_copy)
JLLWrappers.@declare_executable_product(gts_count)
JLLWrappers.@declare_executable_product(gts_dump)
JLLWrappers.@declare_executable_product(gts_filter)
JLLWrappers.@declare_executable_product(gts_get)
JLLWrappers.@declare_executable_product(gts_ls)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libpng_jll, OpenJpeg_jll, libaec_jll)
    JLLWrappers.@init_library_product(
        eccodes,
        "lib/libeccodes.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libeccodes_f90,
        "lib/libeccodes_f90.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        bufr_compare,
        "bin/bufr_compare",
    )

    JLLWrappers.@init_executable_product(
        bufr_copy,
        "bin/bufr_copy",
    )

    JLLWrappers.@init_executable_product(
        bufr_count,
        "bin/bufr_count",
    )

    JLLWrappers.@init_executable_product(
        bufr_dump,
        "bin/bufr_dump",
    )

    JLLWrappers.@init_executable_product(
        bufr_get,
        "bin/bufr_get",
    )

    JLLWrappers.@init_executable_product(
        bufr_index_build,
        "bin/bufr_index_build",
    )

    JLLWrappers.@init_executable_product(
        bufr_ls,
        "bin/bufr_ls",
    )

    JLLWrappers.@init_executable_product(
        bufr_set,
        "bin/bufr_set",
    )

    JLLWrappers.@init_executable_product(
        codes_bufr_filter,
        "bin/codes_bufr_filter",
    )

    JLLWrappers.@init_executable_product(
        codes_count,
        "bin/codes_count",
    )

    JLLWrappers.@init_executable_product(
        codes_export_resource,
        "bin/codes_export_resource",
    )

    JLLWrappers.@init_executable_product(
        codes_info,
        "bin/codes_info",
    )

    JLLWrappers.@init_executable_product(
        codes_parser,
        "bin/codes_parser",
    )

    JLLWrappers.@init_executable_product(
        codes_split_file,
        "bin/codes_split_file",
    )

    JLLWrappers.@init_file_product(
        eccodes_definitions,
        "share/eccodes/definitions",
    )

    JLLWrappers.@init_executable_product(
        grib2ppm,
        "bin/grib2ppm",
    )

    JLLWrappers.@init_executable_product(
        grib_compare,
        "bin/grib_compare",
    )

    JLLWrappers.@init_executable_product(
        grib_copy,
        "bin/grib_copy",
    )

    JLLWrappers.@init_executable_product(
        grib_count,
        "bin/grib_count",
    )

    JLLWrappers.@init_executable_product(
        grib_dump,
        "bin/grib_dump",
    )

    JLLWrappers.@init_executable_product(
        grib_filter,
        "bin/grib_filter",
    )

    JLLWrappers.@init_executable_product(
        grib_get,
        "bin/grib_get",
    )

    JLLWrappers.@init_executable_product(
        grib_get_data,
        "bin/grib_get_data",
    )

    JLLWrappers.@init_executable_product(
        grib_histogram,
        "bin/grib_histogram",
    )

    JLLWrappers.@init_executable_product(
        grib_index_build,
        "bin/grib_index_build",
    )

    JLLWrappers.@init_executable_product(
        grib_ls,
        "bin/grib_ls",
    )

    JLLWrappers.@init_executable_product(
        grib_set,
        "bin/grib_set",
    )

    JLLWrappers.@init_executable_product(
        gts_compare,
        "bin/gts_compare",
    )

    JLLWrappers.@init_executable_product(
        gts_copy,
        "bin/gts_copy",
    )

    JLLWrappers.@init_executable_product(
        gts_count,
        "bin/gts_count",
    )

    JLLWrappers.@init_executable_product(
        gts_dump,
        "bin/gts_dump",
    )

    JLLWrappers.@init_executable_product(
        gts_filter,
        "bin/gts_filter",
    )

    JLLWrappers.@init_executable_product(
        gts_get,
        "bin/gts_get",
    )

    JLLWrappers.@init_executable_product(
        gts_ls,
        "bin/gts_ls",
    )

    JLLWrappers.@generate_init_footer()
    ENV["ECCODES_DEFINITION_PATH"] = eccodes_definitions

end  # __init__()
