# Autogenerated wrapper script for eccodes_jll for x86_64-apple-darwin
export eccodes

using libpng_jll
using OpenJpeg_jll
JLLWrappers.@generate_wrapper_header("eccodes")
JLLWrappers.@declare_library_product(eccodes, "@rpath/libeccodes.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libpng_jll, OpenJpeg_jll)
    JLLWrappers.@init_library_product(
        eccodes,
        "lib/libeccodes.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
